




.build/leonardo/src/mpu9150_raw.cpp : src/mpu9150_raw.ino
	@mkdir -p .build/leonardo/src
	@echo [93msrc/mpu9150_raw.ino[0m
	@/usr/local/bin/ino preproc  -o $@ $^


all : .build/leonardo/src/mpu9150_raw.cpp
	@true

