







	



.build/leonardo/Wire/Wire.d : /usr/share/arduino/libraries/Wire/Wire.cpp
	@mkdir -p .build/leonardo/Wire
	@/usr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/EEPROM  -MM $^ > $@
	
	@printf ".build/leonardo/Wire/Wire.d .build/leonardo/Wire/" | cat - $@ > $@~ && mv $@~ $@

.build/leonardo/Wire/utility/twi.d : /usr/share/arduino/libraries/Wire/utility/twi.c
	@mkdir -p .build/leonardo/Wire/utility
	@/usr/bin/avr-gcc -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=101 -I/usr/share/arduino/hardware/arduino/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -DUSB_VID=0x2341 -DUSB_PID=0x8036 -I/usr/share/arduino/hardware/arduino/variants/leonardo -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Stepper -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/EEPROM  -MM $^ > $@
	
	@printf ".build/leonardo/Wire/utility/twi.d .build/leonardo/Wire/utility/" | cat - $@ > $@~ && mv $@~ $@



.build/leonardo/Wire/dependencies.d : .build/leonardo/Wire/Wire.d .build/leonardo/Wire/utility/twi.d
	@echo [96mScanning dependencies of Wire[0m
	@mkdir -p .build/leonardo/Wire
	@cat $^ > $@;

all : .build/leonardo/Wire/dependencies.d
	@true

